package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
)

type fileEntry struct {
	Path     string
	Content  []byte
	Encoding string
}

func buildWorkflowYaml() string {
	return `name: Deploy GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          enablement: true
`
}

func buildRepositoryReadme(themeName, owner, repoName, pagesURL, themeRepoLink string) string {
	return fmt.Sprintf(`# %s's Portfolio

Deployed using the **%s** theme from [OneClick Portfolio Bot](https://github.com/oneclick-portfolio/op-bot).

## Live Site

%s

## Theme Source

%s

## Local Preview

`+"`python3 -m http.server 8080`"+`

## Credits

Generated by [OneClick Portfolio](https://github.com/oneclick-portfolio) deployer.
`, owner, themeName, pagesURL, themeRepoLink)
}

func transformThemeIndex(indexHTML string) string {
	indexHTML = strings.ReplaceAll(indexHTML, "../../config.js", "./config.js")
	indexHTML = strings.ReplaceAll(indexHTML, "../../src/rxresume.js", "./src/rxresume.js")
	return indexHTML
}

func transformSharedConfig(configJS string) string {
	configJS = strings.ReplaceAll(configJS, "'/resume/Reactive Resume.json'", "'resume/Reactive Resume.json'")
	configJS = strings.ReplaceAll(configJS, "'/src/profile.html'", "'src/profile.html'")
	configJS = strings.ReplaceAll(configJS, "'/favicon.svg'", "'favicon.svg'")
	configJS = strings.ReplaceAll(configJS, "'/favicon.ico'", "'favicon.ico'")
	return configJS
}

func buildThemeBundle(theme, owner, repoName string, resumeData any, sourceRepo, sourceRef, sourceSubDir, themeRepoLink string) ([]fileEntry, error) {
	entries, err := fetchThemeFiles(theme, sourceRepo, sourceRef, sourceSubDir)
	if err != nil {
		return nil, err
	}

	// src/rxresume.js is fetched from a fixed canonical source regardless of
	// which theme repo the caller supplied.
	rxresumeData, err := loadSharedAsset("src/rxresume.js", sharedAssetsRepo, sharedAssetsRef)
	if err != nil {
		return nil, err
	}
	entries = append(entries, fileEntry{Path: "src/rxresume.js", Content: rxresumeData})

	sharedFiles := map[string]string{
		"config.js":   "config.js",
		"favicon.svg": "favicon.svg",
		"favicon.ico": "favicon.ico",
	}

	for source, destination := range sharedFiles {
		data, err := loadSharedAsset(source, sourceRepo, sourceRef)
		if err != nil {
			if destination == "favicon.svg" || destination == "favicon.ico" {
				continue
			}
			return nil, err
		}
		if destination == "config.js" {
			data = []byte(transformSharedConfig(string(data)))
		}
		entries = append(entries, fileEntry{Path: destination, Content: data})
	}

	if resumeData != nil {
		pretty, err := json.MarshalIndent(resumeData, "", "  ")
		if err != nil {
			return nil, fmt.Errorf("unable to serialize resume data: %w", err)
		}
		pretty = append(pretty, '\n')
		entries = append(entries, fileEntry{Path: "resume/Reactive Resume.json", Content: pretty})
	}

	pagesURL := fmt.Sprintf("https://%s.github.io/%s/", owner, repoName)

	entries = append(entries,
		fileEntry{Path: ".github/workflows/deploy-pages.yml", Content: []byte(buildWorkflowYaml())},
		fileEntry{Path: "README.md", Content: []byte(buildRepositoryReadme(getThemeLabel(theme), owner, repoName, pagesURL, themeRepoLink))},
	)

	return entries, nil
}

func fetchThemeFiles(theme, sourceRepo, sourceRef, sourceSubDir string) ([]fileEntry, error) {
	dirPath := sourceSubDir
	if dirPath == "" {
		dirPath = "themes/" + theme
	}
	files, err := fetchThemeDirectory(dirPath, sourceRepo, sourceRef)
	if err != nil {
		return nil, err
	}

	prefix := dirPath + "/"
	entries := make([]fileEntry, 0, len(files))
	for _, f := range files {
		destination := strings.TrimPrefix(f.Path, prefix)
		if destination == "" {
			continue
		}

		content := f.Content
		if path.Base(destination) == "index.html" {
			content = []byte(transformThemeIndex(string(content)))
			destination = "index.html"
		}

		entries = append(entries, fileEntry{
			Path:    destination,
			Content: content,
		})
	}

	if len(entries) == 0 {
		return nil, fmt.Errorf("theme %q has no deployable files", theme)
	}

	return entries, nil
}

func fetchThemeDirectory(dirPath, sourceRepo, sourceRef string) ([]fileEntry, error) {
	parts := strings.Split(dirPath, "/")
	for i, p := range parts {
		parts[i] = url.PathEscape(p)
	}
	escapedPath := strings.Join(parts, "/")
	apiURL := fmt.Sprintf("https://api.github.com/repos/%s/contents/%s?ref=%s", sourceRepo, escapedPath, url.QueryEscape(sourceRef))
	req, err := http.NewRequest(http.MethodGet, apiURL, nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Accept", "application/vnd.github+json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("unable to read theme directory %q from %s: %w", dirPath, sourceRepo, err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		body, readErr := io.ReadAll(resp.Body)
		if readErr != nil {
			return nil, fmt.Errorf("unable to read theme directory error body for %q from %s: %w", dirPath, sourceRepo, readErr)
		}
		return nil, fmt.Errorf("unable to read theme directory %q from %s: status %d: %s", dirPath, sourceRepo, resp.StatusCode, strings.TrimSpace(string(body)))
	}

	type contentItem struct {
		Path        string `json:"path"`
		Type        string `json:"type"`
		DownloadURL string `json:"download_url"`
	}

	var items []contentItem
	if err := json.NewDecoder(resp.Body).Decode(&items); err != nil {
		return nil, fmt.Errorf("unable to decode theme directory listing for %q: %w", dirPath, err)
	}

	entries := make([]fileEntry, 0, len(items))
	for _, item := range items {
		switch item.Type {
		case "dir":
			nested, err := fetchThemeDirectory(item.Path, sourceRepo, sourceRef)
			if err != nil {
				return nil, err
			}
			entries = append(entries, nested...)
		case "file":
			if item.DownloadURL == "" {
				continue
			}
			content, err := fetchRemoteFile(item.DownloadURL)
			if err != nil {
				return nil, fmt.Errorf("unable to fetch theme file %q: %w", item.Path, err)
			}
			entries = append(entries, fileEntry{Path: item.Path, Content: content})
		}
	}

	return entries, nil
}

func fetchRemoteFile(rawURL string) ([]byte, error) {
	resp, err := http.Get(rawURL)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("status %d", resp.StatusCode)
	}

	return io.ReadAll(resp.Body)
}

func loadSharedAsset(relPath, sourceRepo, sourceRef string) ([]byte, error) {
	data, err := fetchRepoFile(relPath, sourceRepo, sourceRef)
	if err != nil {
		return nil, fmt.Errorf("unable to load shared asset %q: %w", relPath, err)
	}
	return data, nil
}

func fetchRepoFile(repoPath, sourceRepo, sourceRef string) ([]byte, error) {
	parts := strings.Split(repoPath, "/")
	for i, p := range parts {
		parts[i] = url.PathEscape(p)
	}
	escapedPath := strings.Join(parts, "/")

	apiURL := fmt.Sprintf("https://api.github.com/repos/%s/contents/%s?ref=%s", sourceRepo, escapedPath, url.QueryEscape(sourceRef))
	req, err := http.NewRequest(http.MethodGet, apiURL, nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Accept", "application/vnd.github+json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("unable to read source file %q from %s: %w", repoPath, sourceRepo, err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		body, readErr := io.ReadAll(resp.Body)
		if readErr != nil {
			return nil, fmt.Errorf("unable to read source file error body for %q from %s: %w", repoPath, sourceRepo, readErr)
		}
		return nil, fmt.Errorf("unable to read source file %q from %s: status %d: %s", repoPath, sourceRepo, resp.StatusCode, strings.TrimSpace(string(body)))
	}

	var item struct {
		Type        string `json:"type"`
		DownloadURL string `json:"download_url"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&item); err != nil {
		return nil, fmt.Errorf("unable to decode source file metadata for %q: %w", repoPath, err)
	}

	if item.Type != "file" || item.DownloadURL == "" {
		return nil, fmt.Errorf("source path %q is not a downloadable file", repoPath)
	}

	return fetchRemoteFile(item.DownloadURL)
}
